# message
command:
  restrict:
    console: "%ERROR% This command must be executed in game."
    player: "%ERROR% This command must be executed from a server console."
  exception:
    sub-registered: "%ERROR% SubCommand with same name / alias for %0 already exists in %1 command"
    pl-cmd-not-found: "%ERROR% %0 command not found in %1 plugin."
config:
  key-not-found: "%ERROR% not found key '%0'"
  invalid-value: "%ERROR% invalid value '%0' from key '%1'"
